### PR TITLE
Modify S-TIP GV to read json files from WebGME. (for #17 issue)

### PR DESCRIPTION
**Pull request by tkhsknsk**
I sent a pull request. Please validate it. ISSUE #17

### CODE REVIEW

**Comment by stmtstk** [comment]
@tkhsknsk 
Thanks for your contribution.
I will check soon.

**Comment by ykoji8681** [comment]
It works for me. I have two comments:

* Remove the old file

  Should we add a removing the old file to the commit?

```
  git rm SharingPolicySpecifications.txt
```

* Doesn't work redaction in "x-stip-sns" field
  - ipv4/email-addr in indicator field: redacted
  - ipv4/email-addr in report field: redacted
  - ipv4/email-addr in x_stip_sns/x_stip_sns_post field: NOT redacted

  I think x-stip-sns/x_stip_sns_post field should be included for redaction.

Thanks, @tkhsknsk !

**Comment by tkhsknsk** [comment]
@ykoji8681 

- Remove the old file
Yes, delete the old configuration file.

- Doesn't work redaction in "x-stip-sns" field
I need to add `"Metatype": "x-stip-sns-model"` to SharingPolicySpecifications.json

-----
- 古いファイルを消しますか？
はい。SharingPolicySpecifications.txtは削除します。

- x-stip-snsフィールドの墨消しについて
SharingPolicySpecifications.jsonに `"Metatype": "x-stip-sns-model"` を追加する必要があります。

**Comment by ykoji8681** [comment]
Thanks, @tkhsknsk .

> Doesn't work redaction in "x-stip-sns" field

It should be a future work for Sharing Policy Enforcement.

Please merge this PR. @stmtstk

**Pull request merged**
